### ISSUE TITLE
CSCS-CI related issues

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#926]
- [ ] Create one HIP pipeline (#846)
- [ ] Add the gcc10 config with APEX (#930)
- [ ] Reenable stdexec in clang14 configuration (#894)  (for now the spack cxx standard for this configuration is 17, the cxx standard for building is 20 and stdexec is disabled)
- [ ] Install pika in configurations (#906)
- [ ] Add CSCS CI pipeline with nvhpc (#925)
- [ ] Reenable gcc12 cuda12 CSCS CI pipeline once cuda driver sufficient on clariden (#884)
- [ ] Try to use the CSCS spack build cache in CI (#789)
- [ ] Reduce duplication in CSCS CI configurations (#862)
- [ ] #962
- [ ] Enable both release and debug build types for all configurations
- [ ] Don't forget to add the `-Wno-error=array-bounds` in the GCC 13 in Release mode (for now we only build debug)
- [ ] Potentially move the configurations to another platform than daint once one is officially available for CI. Clariden is not intended for that but more for ML.
- [ ] Move the performance tests to CSCS CI.

Notes: 
- the gcc11 configuration is using gcc@11.4.0 in CSCS CI whereas it uses gcc@11.2.0 in jenkins
- the gcc9 cuda11 configuration is pinning fmt to version 9

**Comment by msimberg** [comment]
Perhaps worth opening issues for the following as well:
- GCC 10 + APEX configuration
- Release builds
- Performance CI (the one on Jenkins, not the one pushing to elastic)
?
